name: CI

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        varnish:
          - varnish77
          - varnish80
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Varnish from packagecloud
      run: |
        curl -s https://packagecloud.io/install/repositories/varnishcache/${{ matrix.varnish }}/script.deb.sh | sudo bash
        sudo apt-get update
        sudo apt-get install -y varnish varnish-dev

    - name: Build VMOD
      run: cargo build --release

    - name: Run tests
      run: cargo test
