name: CI

# Controls when the action will run.
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
        varnish:
          - "https://varnish-cache.org/_downloads/varnish-8.0.0.tgz" #VRT=22.0
          - "https://varnish-cache.org/_downloads/varnish-7.7.0.tgz" #VRT=19.0
        include:
          - varnish: "https://github.com/varnishcache/varnish-cache/archive/master.tar.gz"
            allow_failures: "true"
    steps:
      - uses: actions/checkout@v2
      - name: install build depends
        run: sudo apt-get install python3-docutils python3-sphinx
      - name: build varnish
        run: |
          wget ${{ matrix.varnish }}
          tar -zxf *gz
          pushd varnish-*/
          ./autogen.sh
          ./configure --prefix=/usr
          make -sj32
          sudo make install
          popd
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
      - name: build vmod
        run: |
          cd $GITHUB_WORKSPACE
          ./autogen.sh
          ./configure --prefix=/usr
          make -j4
          make check -j4
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
